apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: idserver
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: idserver
        component: idserver
    spec:
      containers:
      - name: idserver
        image: eu.gcr.io/cellarstone-1488228226623/idserver:dev.0.0.23
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registry-key
