apiVersion: v1
kind: Service
metadata:
  labels:
    app: idserver
    component: idserver
  name: idserver
spec:
  selector:
    app: idserver
    component: idserver
  ports:
   - port: 80
  type: ClusterIP
